name: Deploy HTML Site

on:
  push:
    branches:
      - main  # Triggers the workflow on every push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Combine the split ZIP parts into a single file
      - name: Combine split ZIP parts
        run: cat html_site_part_*.zip > html_site_combined.zip

      # Step 3: Unzip the combined file into the root directory
      - name: Unzip combined ZIP file to root
        run: unzip html_site_combined.zip -d ./
        
      # Step 4: Deploy to GitHub Pages (if using GitHub Pages from the 'gh-pages' branch)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./  # This ensures everything at the root is deployed
