name: Deploy HTML Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Install Unzip Tool
      - name: Install unzip
        run: sudo apt-get install unzip

      # Step 3: Unzip the uploaded HTML folder
      - name: Unzip HTML folder
        run: unzip html_site.zip -d html_site

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html_site  # Directory containing unzipped HTML files
